services:
  osparc-python-runner:
    build:
      labels:
        io.simcore.authors: '{"authors": [{"name": "Sylvain Anderegg", "email": "anderegg@itis.swiss",
          "affiliation": "IT''IS Foundation"}, {"name": "Pedro Crespo", "email": "32402063+pcrespov@users.noreply.github.com",
          "affiliation": "IT''IS Foundation"}]}'
        io.simcore.contact: '{"contact": "anderegg@itis.swiss"}'
        io.simcore.description: '{"description": "oSparc Python Runner"}'
        io.simcore.inputs: '{"inputs": {"input_1": {"displayOrder": 1, "label": "Input
          data", "description": "Any code, requirements or data file", "type": "data:*/*"}}}'
        io.simcore.integration-version: '{"integration-version": "1.0.0"}'
        io.simcore.key: '{"key": "simcore/services/comp/osparc-python-runner"}'
        io.simcore.name: '{"name": "oSparc Python Runner"}'
        io.simcore.outputs: '{"outputs": {"output_1": {"displayOrder": 1, "label":
          "Output data", "description": "All data produced by the script is zipped
          as output_data.zip", "type": "data:*/*", "fileToKeyMap": {"output_data.zip":
          "output_1"}}}}'
        io.simcore.type: '{"type": "computational"}'
        io.simcore.version: '{"version": "1.1.0"}'
        org.label-schema.build-date: ${BUILD_DATE}
        org.label-schema.schema-version: '1.0'
        org.label-schema.vcs-ref: ${VCS_REF}
        org.label-schema.vcs-url: https://github.com/ITISFoundation/osparc-python-runner
version: '3.7'
